### ISSUE TITLE
Modify build script to output module for use with Lit

### ISSUE THREAD

**Issue by adaburrows** [neighbour-hoods/nh-design-system#8]
Create a build script that wraps the css files for use with lit (it expects a sting). Look at https://github.com/jleeson/rollup-plugin-import-css/blob/master/src/index.js#L49 for an example of how they are generating the string.

That file might also be useful for other formats if we need it.

**Comment by nick-stebbings** [comment]
I have tried doing this but to no avail, will need a bit of help finalising this task. We are using `rollup-plugin-import-css` in the build process already but I have not been able to get this to export something that will inject into a Lit component.
See https://github.com/neighbour-hoods/nh-design-system/commit/fa7040a4f7f79951c3b07fb60ce1135341fa598d
@adaburrows
